language: python
python:
  # - "2.7"
  # - "3.4"
  # - "3.5"
  # - "3.6"      # current default Python on Travis CI
  # - "3.7"
  - "3.8"
  # - "3.8-dev"  # 3.8 development branch
  # - "nightly"  # nightly build
os: linux
# command to install dependencies

install:
  #copy pasted (with minor modification) from https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Create conda environment 
  - conda env create -f cfl_env.yml
  - conda activate cfl-environment
  - python setup.py install
# command to run tests
script:
  - pytest