# NOTE: this file contains somewhat repeated information with the requirements.txt on
# main branch 
# (the difference is that requirements.txt is for pip installing dependencies
# and this requirements.yml is for creating a conda virtual environment with the
# dependencies for cfl )
# TODO: this file may be useful if you clone the repository, but right now is not
# used/referenced in our current setup instructions

# this file contains the requirements for the cfl package

# to create a conda environment from this file, run the commands:
#     conda env create -f requirements.yml
#     conda activate cfl-env

# to generate a new version of this file from the current environment, run the command:
#     conda env export --from-history > requirementsNEW.yml

name: cfl-env
channels:
  - defaults
  - conda-forge
dependencies:
  - tqdm # progress bar
  - matplotlib=3.3.1  # creates plots (used for visualization)
  - tensorflow  # machine learning
  - keras
  - numpy=1.19.2 # array manipulation and fast computing # needs to be >1.17
  - scikit-learn=0.23.2 # used to import clustering methods and other algorithms/metrics
  - jupyter # for jupyter notebooks
  - ipykernel # to add dependencies to kernel during set-up
  - keras


# # the following packages are not required to use the basic
# # cfl code, but may be needed to run some of the example notebooks
# # or testing code.
  - pytest=6.0.1 # to run regression tests
  - pandas # for formatting data frames (eg used for fear mice data)
  - nibabel # for reading/writing MRIs
  - ipywidgets  # for interactive widgets
  - jupyter_nbextensions_configurator
  - plotly # for the sankey diagrams
