# this file contains the requirements for the cfl package

# to create a conda environment from this file, run the commands:
#     conda env create -f requirements.yml
#     conda activate cfl-env

# to generate a new version of this file from the current environment, run the command:
#     conda env export --from-history > requirementsNEW.yml

name: cfl-env
channels:
  - defaults
  - conda-forge
dependencies:
  - tqdm # progress bar
  - matplotlib=3.3.1  # creates plots (used for visualization)
  - tensorflow  # machine learning
  - keras
  - numpy=1.19.2 # array manipulation and fast computing
  - scikit-learn=0.23.2 # used to import clustering methods and other algorithms/metrics
  - jupyter # for jupyter notebooks
  - ipykernel # to add dependencies to kernel during set-up

# # the following packages are not required to use the basic
# # cfl code, but may be needed to run some of the example notebooks
# # or testing code.
  - joblib=0.16.0 # used to save/load data primarily for el nino example
  - pytest=6.0.1 # to run regression tests
  - pandas # for formatting data frames (eg used for fear mice data)
  - nibabel # for reading/writing MRIs
  - ipywidgets  # for interactive widgets
  - jupyter_nbextensions_configurator